require "rubygems"
require "tmpdir"

require "bundler/setup"
require "jekyll"


# Change your GitHub reponame
GITHUB_REPONAME = "zadaianchuk/zadaianchuk.github.io"


desc "Generate blog files"
task :generate do
  Jekyll::Site.new(Jekyll.configuration({
    "source"      => ".",
    "destination" => "_site"
  })).process
end


desc "Generate and publish blog to gh-pages"
task :publish => [:generate] do
  Dir.mktmpdir do "/Users/azadaianchuk/projects/website/projects/new_dir"
    cp_r "_site/.", "/Users/azadaianchuk/projects/website/projects/new_dir"

    pwd = Dir.pwd
    Dir.chdir "/Users/azadaianchuk/projects/website/projects/new_dir"

    system "git init"
    system "git add ."
    message = "Site updated at #{Time.now.utc}"
    system "git commit -m #{message.inspect}"
    system "git remote add origin git@github.com:#{GITHUB_REPONAME}.git"
    system "git push origin master --force"

    Dir.chdir pwd
  end
end
